'use strict';

const {
  DEFAULT_COUNT,
  INTERVAL_IN_MONTHS,
  MIN_COUNT,
  MAX_COUNT,
  DEFAULT_COMMAND,
  DEFAULT_PORT,
  FRONT_CLIENT_PORT,
  PUBLIC_DIR,
  TEMPLATES_DIR,
  UTF8_ENCODING_FORMAT,
  USER_ARGV_INDEX,
  HOME_PATH,
  NOT_FOUND_MESSAGE_TEXT,
  ExitCode,
  HttpCode,
} = require(`./common`);

const {
  FILE_NAME,
  FILE_SENTENCES_PATH,
  FILE_TITLES_PATH,
  FILE_CATEGORIES_PATH,
  AnnounceRestrict,
} = require(`./mocksGeneration`);

module.exports = {
  DEFAULT_COUNT,
  INTERVAL_IN_MONTHS,
  MIN_COUNT,
  MAX_COUNT,
  DEFAULT_COMMAND,
  DEFAULT_PORT,
  FRONT_CLIENT_PORT,
  PUBLIC_DIR,
  TEMPLATES_DIR,
  UTF8_ENCODING_FORMAT,
  USER_ARGV_INDEX,
  HOME_PATH,
  NOT_FOUND_MESSAGE_TEXT,
  ExitCode,
  HttpCode,
  FILE_NAME,
  FILE_SENTENCES_PATH,
  FILE_TITLES_PATH,
  FILE_CATEGORIES_PATH,
  AnnounceRestrict,
};
