'use strict';

const {
  DEFAULT_COUNT,
  INTERVAL_IN_MONTHS,
  MIN_COUNT,
  MAX_COUNT,
  DEFAULT_COMMAND,
  UTF8_ENCODING_FORMAT,
  USER_ARGV_INDEX,
  ExitCode,
} = require(`./common`);

const {
  FILE_NAME,
  FILE_SENTENCES_PATH,
  FILE_TITLES_PATH,
  FILE_CATEGORIES_PATH,
  AnnounceRestrict,
} = require(`./mocksGeneration`);

module.exports = {
  DEFAULT_COUNT,
  INTERVAL_IN_MONTHS,
  MIN_COUNT,
  MAX_COUNT,
  DEFAULT_COMMAND,
  UTF8_ENCODING_FORMAT,
  USER_ARGV_INDEX,
  ExitCode,
  FILE_NAME,
  FILE_SENTENCES_PATH,
  FILE_TITLES_PATH,
  FILE_CATEGORIES_PATH,
  AnnounceRestrict,
};
